services:
  next-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - frontend
