services:
  next-app:
    build: 
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile.dev
    ports:
      - 3000
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8083:8080"
    volumes:
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on:
      - next-app
