import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/redux/provider";
import { Navbar, Footer } from "@/components/common";
import { Cookies, Setup } from "@/components/utils";
import { cookies } from 'next/headers'

import { getSession, setSession } from "@/session";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Laced",
  description: "Generated by create next app",
};

async function getRequest() {
  const res = await fetch(
    // `${process.env.NEXT_PUBLIC_HOST}/api/${url}`,
    `http://127.0.0.1:3000/api/cookies/`,
    {
      cache: "no-store",
      headers: {
        // Authorization: `JWT ${cookies.access}`,
        // Authorization: `JWT ${cookies().get('access')?.value}`,
        // Cookie: sessionid || '', // Устанавливаем куки в формате "имя=значение"
        Cookie: cookies(), // Устанавливаем куки в формате "имя=значение"
        // sessionid: sessionid || '', // Устанавливаем куки в формате "имя=значение"
      },
      credentials: "include",
    },
  );

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return await res;
  // return await res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const a = await getRequest()
  // // console.log('------------------------------',a.text)
  // console.log('++++++++++++++++++++++++++++++', cookies().getAll())
  // // const session = await getSession();
  // // console.log('||||||||||||||||||||||||||||||', cookies().getAll())
  // console.log('||||||||||||||||||||||||||||||', a.headers.getSetCookie())


  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Setup />
          {/* <Cookies view={!preferencesIsSet ? true : false} /> */}
          <Cookies />
          <div className="bg-[#FAF9F8] min-h-screen flex flex-col">
            <Navbar />
            <div className="flex-grow">{children}</div>
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
