import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/redux/provider";
import { Navbar, Footer } from "@/components/common";
import { Cookies, Setup } from "@/components/utils";
import { Suspense } from "react";
import { NavigationEvents } from "@/components/utils/navigation-events";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Laced",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const preferencesIsSet = cookieStore.get("sessionid");

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Setup />
          <Cookies view={preferencesIsSet ? true : false} />
          <Navbar />
          <div className="bg-[#FAF9F8]">{children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
