# Generated by Django 4.2.7 on 2024-01-15 22:54

import app.purchases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('RU', 'Russian Federation'), ('KZ', 'Kazakhstan'), ('BY', 'Belarus')], default='RU', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('KZT', 'Kazakhstani Tenge'), ('BYN', 'Belarusian Ruble')], default='RUB', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='purchases.country')),
                ('currency', models.ForeignKey(default=app.purchases.models.Currency.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='preferred_currency', to='purchases.currency')),
                ('location', models.ForeignKey(default=app.purchases.models.Country.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='preferred_location', to='purchases.country')),
            ],
        ),
    ]
