# Generated by Django 4.2.7 on 2024-01-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
    ]
