# Generated by Django 4.2.7 on 2024-01-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_account_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='locale',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English')], max_length=2, null=True),
        ),
    ]
