# Generated by Django 4.2.7 on 2024-01-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_account_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
