# Generated by Django 4.2.7 on 2024-01-15 22:54

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ManyToManyField(related_name='country', to='purchases.country'),
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price', to='purchases.currency'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='product.productitem'),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='products',
            field=models.ManyToManyField(related_name='carousel', to='product.product'),
        ),
        migrations.AddField(
            model_name='availablevariationoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='availablevariationoption',
            name='variation_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.variationoption'),
        ),
        migrations.AddField(
            model_name='accountproduct',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.account'),
        ),
        migrations.AddField(
            model_name='accountproduct',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productitem'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug', 'name'], name='product_pro_slug_112db2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GistIndex(fields=['data'], name='product_pro_data_c02424_gist'),
        ),
    ]
